version: '3.8'
services:
  web:
    build: 
      context: .
    environment:
      - NEXT_PUBLIC_API_MAP_KEY
  nginx:
    build:
      context: ./nginx/
    ports:
      - 443:443
      - 80:80
    volumes:
      - $PWD/certs:/etc/nginx/certs
  echo:
    image: ealen/echo-server
