AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  RSVPDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "code"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "code"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "rsvp"